### PR TITLE
DDF-1325: Made the CSW Source query type configurable

### PR DESCRIPTION
**Pull request by jlcsmith**
- query type qname and prefix is configurable
- removed dependency on CSW Record MetacardType
- added query mapping for id attribute

@millerw8 @kcwire @wmcnalli @beyelerb @emanns95 @coyotesqrl

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-spatial/40)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
:+1:

**Comment by duckbyte** [comment]
+1

**Comment by kcwire** [comment]
Looks good - who is the hero for this ticket?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/40)

**Comment by jlcsmith** [comment]
I nominate @wmcnalli.  I have at least one more change pending though.  I missed that CswSource.setFilterDelegate() was still taking a CswRecordMetacardType.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/40)

**Comment by jlcsmith** [comment]
Closed to https://github.com/codice/ddf-catalog/pull/115

**Pull request closed without merging**
