### PR TITLE
DDF-1219 Collapsing, normalizing, and refactoring unit tests. There are more opportunities for refactoring, but this represents approximately a 15% reduction in class size and removes much of the duplicate code.

### PR DESCRIPTION
**Pull request by coyotesqrl**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-spatial/29)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
*I hope I'm notifying correctly here; please let me know if I should be doing this differently.*

So...have at it @jlcsmith @shaundmorris @stustison @pklinef @figliold @kcwire @beyelerb @millerw8

**Comment by kcwire** [comment]
LGTM.  Will merge today if there are no objections.

**Comment by shaundmorris** [comment]
:+1: nice refactor

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java @ r2

---

<sup>**[wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java, line 43 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/29#-Jqu5Wr1zLhQUDXK0HpH)** ([raw file](https://github.com/codice/ddf-spatial/blob/1eebffb58dbacb0f409cf2857464d100a11068b0/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java#L43)):</sup>
We have been avoiding '*' in the package declarations. May just be your default Intellij settings.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/29)

**Comment by coyotesqrl** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java, line 43 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/29#-Jqu5Wr1zLhQUDXK0HpH)** ([raw file](https://github.com/codice/ddf-spatial/blob/1eebffb58dbacb0f409cf2857464d100a11068b0/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java#L43)):</sup>
Must be. I think that was when I was using the DDF version of the code formatter. I've since loaded the one from DIB and just checked to be sure it won't collapse package imports. Sorry about that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/29)

**Pull request merged**
