### PR TITLE
DDF-1013:  Added temporal fallback to Wfs 2.0 Filter Delegate for unsupp...

### PR DESCRIPTION
**Pull request by dyerkyle**
DDF-1013:  Added temporal fallback to Wfs 2.0 Filter Delegate for unsupported temporal operators

### CODE REVIEW

**Comment by shaundmorris** [comment]
@dyerkyle  can you take a look at your formatter? We may have to look into this more, you may very well be fine, but it seems like a lot of developers are starting to reformat each other's code.

**Comment by dyerkyle** [comment]
Will do.  Do we have a global config out on a wiki somewhere?

**Comment by kcwire** [comment]
Formatter
https://tools.codice.org/wiki/display/DDF/Formatting+Source+Code

**Comment by dyerkyle** [comment]
Closing pull request and opening new one with latest

**Comment by dyerkyle** [comment]
I've pushed an update to the Unit Tests for this PR. Please review.

**Comment by shaundmorris** [comment]
@dyerkyle unit tests look good to me. Also looks like you are using the correct formatter.

**Pull request merged**
