### PR TITLE
DDF-1139 - updated CswEndpoint to provide the list of federated sourc…

### PR DESCRIPTION
**Pull request by kcwire**
…es in the Capabilities document. CswEndpoint can now support queries to specific sources.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-spatial/30)

### CODE REVIEW

**Comment by kcwire** [comment]
@shaundmorris @jlcsmith @millerw8 @pklinef

**Comment by jlcsmith** [comment]
Review status: 0 of 5 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 643 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrJPMmCXkHeqD4Rn5MW)** ([raw file](https://github.com/codice/ddf-spatial/blob/6af25c128ef1200acf42fa3af4729c04b0a336bc/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L643)):</sup>
Perhaps make distributed isDistributed?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by jlcsmith** [comment]
Review status: 0 of 5 files reviewed, 2 unresolved discussions, some commit checks pending.

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 646 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrJQQxHrvXIhwTGP-8D)** ([raw file](https://github.com/codice/ddf-spatial/blob/6af25c128ef1200acf42fa3af4729c04b0a336bc/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L646)):</sup>
use CollectionUtils.isEmpty() instead

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by jlcsmith** [comment]
It might be worthwhile to have an example in the documentation of this type of query.

---

Review status: 0 of 5 files reviewed, 2 unresolved discussions, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by kcwire** [comment]
Updated the GetCapabilities Response and added a sample query in the GetRecords section of the docs.

---

Review status: 0 of 5 files reviewed, 2 unresolved discussions, some commit checks broke.

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 643 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrJPMmCXkHeqD4Rn5MW)** ([raw file](https://github.com/codice/ddf-spatial/blob/6af25c128ef1200acf42fa3af4729c04b0a336bc/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L643)):</sup>
done

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 646 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrJQQxHrvXIhwTGP-8D)** ([raw file](https://github.com/codice/ddf-spatial/blob/6af25c128ef1200acf42fa3af4729c04b0a336bc/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L646)):</sup>
done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by pklinef** [comment]
Review status: 0 of 7 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 1047 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrT-43ypi7s4uxoCTEz)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L1047)):</sup>
Is there a reason you can't use Set instead of List when dealing with the collection of source ids?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by pklinef** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java @ r1
- csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java @ r2
- csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java @ r1
- csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/TestCswRecordMapperFilterVisitor.java @ r1
- csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java @ r1
- docs/src/main/resources/Integrating.adoc @ r2
- pom.xml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by shaundmorris** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.
Reviewed files:
- csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java @ r1
- csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java @ r2
- csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java @ r1
- csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/TestCswRecordMapperFilterVisitor.java @ r1
- csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java @ r1
- docs/src/main/resources/Integrating.adoc @ r2
- pom.xml @ r2

---

<sup>**[docs/src/main/resources/Integrating.adoc, line 455 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrURs_YZTpLfr78XiBN)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/docs/src/main/resources/Integrating.adoc#L455)):</sup>
Is it possible to make the source-id specifics bold? The average reader might get lost in the example (although it is a good one) due to its size.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by kcwire** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 1047 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrT-43ypi7s4uxoCTEz)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L1047)):</sup>
unfortunately no. The underlying JAXB binding is expecting a List<String>.

---

<sup>**[docs/src/main/resources/Integrating.adoc, line 455 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrURs_YZTpLfr78XiBN)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/docs/src/main/resources/Integrating.adoc#L455)):</sup>
I looked around but didn't see a way to add markup within a source block.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by shaundmorris** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[docs/src/main/resources/Integrating.adoc, line 455 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrURs_YZTpLfr78XiBN)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/docs/src/main/resources/Integrating.adoc#L455)):</sup>
Okay thanks for checking. It is a good example just was wondering if we could make it a little easier.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by millerw8** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 649 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-Jrd7lGJ5QfPV66ccRaI)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L649)):</sup>
don't need second part of if

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java, line 314 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrdA-M7F82N2b5agh0C)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java#L314)):</sup>
Why were these needed?  were filters embedded in boolean logic not passing through the visitor?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Comment by kcwire** [comment]
Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java, line 314 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/30#-JrdA-M7F82N2b5agh0C)** ([raw file](https://github.com/codice/ddf-spatial/blob/f32205d03f27557cc23502bdde15861fc0a409d7/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/mappings/CswRecordMapperFilterVisitor.java#L314)):</sup>
so we can remove empty or null filters when the source-id filter gets removed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/30)

**Pull request merged**
