### PR TITLE
DDF-1174 Adding jacoco config to DDF-Spatial

### PR DESCRIPTION
**Pull request by andrewkfiedler**
The top pom defers to the DDF-Parent configuration, but the rest of the poms have custom configurations for the minimum code coverage required (determined by an initial run with jacoco, with a subtraction of 5 percent to give some room).

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-spatial/25)

### CODE REVIEW

**Comment by lessarderic** [comment]
<sup>**[docs/pom.xml, line 42 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/25#-Jnx54fI7ax3iX8h7Q_k)** ([raw file](https://github.com/codice/ddf-spatial/blob/126937faf869788aef168a5331565c4b48cc8ba5/docs/pom.xml#L42)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/25)

**Comment by lessarderic** [comment]
<sup>**[ogc/spatial-ogc-api/pom.xml, line 47 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/25#-Jnx5E4g39UGE4zHL8jS)** ([raw file](https://github.com/codice/ddf-spatial/blob/126937faf869788aef168a5331565c4b48cc8ba5/ogc/spatial-ogc-api/pom.xml#L47)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/25)

**Comment by lessarderic** [comment]
<sup>**[wfs/1.0.0/spatial-wfs-v1_0_0-schema-webapp/pom.xml, line 45 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/25#-Jnx5SV0abr64XHWJRi5)** ([raw file](https://github.com/codice/ddf-spatial/blob/126937faf869788aef168a5331565c4b48cc8ba5/wfs/1.0.0/spatial-wfs-v1_0_0-schema-webapp/pom.xml#L45)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/25)

**Comment by lessarderic** [comment]
<sup>**[wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml, line 146 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/25#-Jnx5XLcLWPBJEvEAZT4)** ([raw file](https://github.com/codice/ddf-spatial/blob/126937faf869788aef168a5331565c4b48cc8ba5/wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml#L146)):</sup>
Fix indentation.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/25)

**Comment by lessarderic** [comment]
<sup>**[wfs/spatial-wfs-api/pom.xml, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-spatial/25#-Jnx5d9vfvYHgNHON3dc)** ([raw file](https://github.com/codice/ddf-spatial/blob/126937faf869788aef168a5331565c4b48cc8ba5/wfs/spatial-wfs-api/pom.xml#L54)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/25)

**Comment by shaundmorris** [comment]
Reviewed files:
- csw/pom.xml @ r2
- csw/spatial-csw-common/pom.xml @ r2
- csw/spatial-csw-endpoint/pom.xml @ r2
- csw/spatial-csw-schema-bindings/pom.xml @ r2
- csw/spatial-csw-source/pom.xml @ r2
- csw/spatial-csw-transformer/pom.xml @ r2
- docs/pom.xml @ r2
- kml/pom.xml @ r2
- kml/spatial-kml-app/pom.xml @ r2
- kml/spatial-kml-networklinkendpoint/pom.xml @ r2
- kml/spatial-kml-transformer/pom.xml @ r2
- ogc/pom.xml @ r2
- ogc/spatial-ogc-api/pom.xml @ r2
- ogc/spatial-ogc-common/pom.xml @ r2
- ogc/spatial-ogc-urlresourcereader/pom.xml @ r2
- pom.xml @ r1
- spatial-app/pom.xml @ r2
- wcs/pom.xml @ r2
- wcs/spatial-wcs-common/pom.xml @ r2
- wfs/1.0.0/pom.xml @ r2
- wfs/1.0.0/spatial-wfs-v1_0_0-common/pom.xml @ r2
- wfs/1.0.0/spatial-wfs-v1_0_0-converter/pom.xml @ r2
- wfs/1.0.0/spatial-wfs-v1_0_0-endpoint/pom.xml @ r2
- wfs/1.0.0/spatial-wfs-v1_0_0-schema-bindings/pom.xml @ r2
- wfs/1.0.0/spatial-wfs-v1_0_0-schema-webapp/pom.xml @ r2
- wfs/1.0.0/spatial-wfs-v1_0_0-source/pom.xml @ r2
- wfs/2.0.0/pom.xml @ r2
- wfs/2.0.0/spatial-wfs-v2_0_0-common/pom.xml @ r2
- wfs/2.0.0/spatial-wfs-v2_0_0-converter/pom.xml @ r2
- wfs/2.0.0/spatial-wfs-v2_0_0-schema-bindings/pom.xml @ r2
- wfs/2.0.0/spatial-wfs-v2_0_0-source/pom.xml @ r2
- wfs/pom.xml @ r2
- wfs/spatial-wfs-api/pom.xml @ r2
- wfs/spatial-wfs-common/pom.xml @ r2
- wfs/spatial-wfs-converter/pom.xml @ r2
- wfs/spatial-wfs-mapper/pom.xml @ r2
- wfs/spatial-wfs-source/pom.xml @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/25)

**Pull request merged**
