### PR TITLE
DDF-1270: separated headers from content in documentation files for

### PR DESCRIPTION
**Pull request by ricklarsen**
These changes will enable all documentation to be compiled into a single pdf for publication.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-spatial/37)

### CODE REVIEW

**Comment by ricklarsen** [comment]
@shaundmorris @pklinef @smithjosh

**Comment by SmithJosh** [comment]
The *Contents.adoc files you created are being processed by asciidoctor and packaged into the documentation zip that gets deployed to nexus. They should be excluded from the archive to keep the documentation as clean as possible. The exclusions are specified in ddf-spatial/docs/src/assembly/bin.xml

**Comment by SmithJosh** [comment]
Verified that build succeeds, all tests pass, and the maven-assembly-plugin exclusions work correctly.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by shaundmorris** [comment]
Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[docs/src/main/resources/IntContents.adoc, line 1 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/37#-JsgYBTrR9w7L0Aoe_cC)** ([raw file](https://github.com/codice/ddf-spatial/blob/e8de4c8067aae7107d867c65a422a4b1e299a4d8/docs/src/main/resources/IntContents.adoc#L1)):</sup>
I liked this "Integrating" since "Int" is more like an integer :-) but that could just be me.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by ricklarsen** [comment]
<sup>**[docs/src/main/resources/IntContents.adoc, line 1 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-spatial/37#-JsgYBTrR9w7L0Aoe_cC)** ([raw file](https://github.com/codice/ddf-spatial/blob/e8de4c8067aae7107d867c65a422a4b1e299a4d8/docs/src/main/resources/IntContents.adoc#L1)):</sup>
That's a good point. I didn't change it because it's going to get included in the overall integrating page and never stand alone. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by ricklarsen** [comment]
fixed

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by pklinef** [comment]
:+1:

**Comment by kcwire** [comment]
Can we merge this?

**Comment by clockard** [comment]
There is a ManContents.adoc but not a Maintenance.adoc

---

Reviewed 6 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by ricklarsen** [comment]
A-ha, it was missing the changes. Fixed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by clockard** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by clockard** [comment]
:+1:

**Comment by AzGoalie** [comment]
Reviewed 6 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-spatial/37)

**Comment by ricklarsen** [comment]
Repo deprecated. Changes moved into ddf-catalog/spatial

**Pull request closed without merging**
